### PR TITLE
Gray background, policy cart, and other UI fixes to Mobile

### LINKED ISSUE #930: Add gray background to policy cart and buttons on mobile
As we have on the desktop view. It can remove the `Your policy` header, as I think it'll be clear from the shading and Baseline/Reform buttons.

image

image

### PR DESCRIPTION
**Pull request by Felix-Cadiz**
Fixes #930
- Gray background was added to mobile.
- "Your Policy" headline was removed.
- Compute buttons on "Policy" and "Your Household" are now part of the same row as the rest of the "Your Policy" section.

### CODE REVIEW

**Comment by Felix-Cadiz** [comment]
Images to show the updated version.

Screen Shot 2022-09-19 at 12 22 18 PM
Screen Shot 2022-09-19 at 12 22 32 PM

**Comment by MaxGhenis** [comment]
Thanks @Felix-Cadiz looks great. I agree with your choice for one reform provision per screen. Could you show how it looks centered to align with the other elements in the box? This might also look more natural on desktop.

**Comment by Felix-Cadiz** [comment]
Here is it with the policy centered on mobile. This does not affect the Desktop view. 

Let me know what you think. I will push a new commit if we decide to have the policy centered.

Screen Shot 2022-09-19 at 1 26 55 PM

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Nice, yes let's center.

**Comment by Felix-Cadiz** [comment]
With the latest push, policies are now centered. This branch is ready to be merged.

**Comment by Felix-Cadiz** [comment]
With the latest push, policies are now centered. This branch is ready to be merged and deployed.

**Pull request merged**
