### PR TITLE
Use a solid zero line

### LINKED ISSUE #232: Use a solid zero line
Instead of dashed

If it's too strong, make it a lighter gray or thinner

https://github.com/PolicyEngine/policyengine/blob/e3f9de28e54a473eb7eb36a2ef3cad72463d6387/policyengine/utils/charts.py#L269

### PR DESCRIPTION
**Pull request by tolaouk**
fixes #232

### CODE REVIEW

**Comment by tolaouk** [comment]
@MaxGhenis Do I need to do some kinda set up to test this?

**Review by nikhilwoodruff — APPROVED** [review]
Thanks @tolaouk - the test fail is fixed in #234 , so I'll rerun once that's merged later today. This looks good to merge after that!

**Comment by MaxGhenis** [comment]
@tolaouk could you share a screenshot of a graph or two once you get the app running?

**Comment by tolaouk** [comment]
> @tolaouk could you share a screenshot of a graph or two once you get the app running?

Yes i'll do that.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff could you help set up @tolaouk with the FRS data?

See also #261, it wasn't immediately clear that this was the issue when he tried running it.

**Pull request merged**
