### PR TITLE
Generalisation

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
This is a significant change - instead of having `policyengine-X` repos, we'll consolidate variable/parameter metadata in the `openfisca-X` repos alongside their definitions, and instead have this repo become `policyengine/policyengine` (with a client React app, and a Flask server). This will significantly reduce dependency complexity and streamline a lot of the code.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Will we then transfer issues from `policyengine-xx` repos to `openfisca-xx` or `policyengine` repos?

**Comment by MaxGhenis** [comment]
Also seems like this increases the importance of moving custom reforms to a separate repo.

**Comment by nikhilwoodruff** [comment]
> Will we then transfer issues from `policyengine-xx` repos to `openfisca-xx` or `policyengine` repos?

I think we should, yes

**Comment by nikhilwoodruff** [comment]
> Also seems like this increases the importance of moving custom reforms to a separate repo.

Potentially, but right now we only have one Python file handling all custom reforms

**Pull request merged**
