### PR TITLE
Add landing page

### LINKED ISSUE #444: Landing page
https://policyengine.org should be a friendly screen that points people most prominently to https://policyengine.org/uk, but also has our blog, about page, FAQ, social media, etc.

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #444

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Here's a first draft: 
image

**Comment by MaxGhenis** [comment]
@nmrodelo suggested fading the US flag, since it's currently more prominent than the UK flag

**Comment by nikhilwoodruff** [comment]
Here's an updated version:

### Main page
image

### Scrolled down

image

### Footer

image

**Comment by nikhilwoodruff** [comment]
I thought the top bar looked conspicuously empty, so added the Home/About/Contact as these seem the most standard. These won't show on the actual app pages, but could do.

**Pull request merged**
