### PR TITLE
Add time travel capability

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
# New feature: Time travel

This adds a 'time travel' parameter - a date which sets the policy date of both the baseline and reform simulations. This ended up being slightly complex because the parameters need to be fetched with the current date, which is itself a policy parameter.

To go:
- [x] The UC reform is back now, but for some reason the results are inverted (i.e. the baseline and policy reforms are the wrong way round- trying to find out where this happens)

### Status
- [x] Cosmetic change
  - [x] Screenshots attached
- [x] Back-end change
  - [x] Unintuitive logic commented
- [x] Version change
  - [x] Minor

#### Before entry
image
#### Entering a date
image
### Immediately after entering a date
This shows the changes in parameter - the time travel component fetches the parameters at the specified dates, and updates only the default values, leaving all the parameter values the same.
image

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Recapping our meeting:
1. Rename to `Baseline snapshot`
2. Adjusting the baseline snapshot will reset all the parameters (mention this in the description)
3. Also add a date-picker and button to set the reform parameters as of a particular date - this doesn't itself change a new parameter, it only changes other parameters (a la AutoUBI)

To add to (3), it could be worth a separate `Reform to today's policy` button.

**Comment by nikhilwoodruff** [comment]
@MaxGhenis - OK, the component now works like your comment. We can check it in the meeting later, but should be good to go.

**Comment by MaxGhenis** [comment]
I get this when clicking the General tab from the Policy page:
image

I imagine this is because I haven't done the find-replace command to point the client to the local server, but I no longer see that in the README.

But if you're confident it works, let's launch it.

**Comment by nikhilwoodruff** [comment]
@MaxGhenis added that instruction back to the README. I'm going to test deploy briefly and if that's without bugs then I'll merge this.

**Comment by nikhilwoodruff** [comment]
@MaxGhenis I found one last bug when testing it - we need to pass both the parameter for the baseline and reform simulation dates, as the app only sends parameters to the API when those differ from the default values. If you like, I could just manually hide the reform date if it's confusing though. Other than that, I think we're good to merge

**Pull request merged**
