### PR TITLE
light gray shading implemented for desktop view.

### PR DESCRIPTION
**Pull request by Felix-Cadiz**
Light gray shading is implemented for desktop view through inline CSS to match the rest of the app. Please advise if the shading should be darker, should cover the entire column, or any other thoughts. 

Screen Shot 2022-08-10 at 8 17 03 AM

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks @Felix-Cadiz! A few thoughts:
* Color shade looks good
* We'll need a transparent-background link icon to match the Twitter icon
* Could you shrink the button widths so there's some buffer?
* Let's make it the full column
* Could you drop a screenshot of how it looks on mobile?

**Review by nikhilwoodruff — COMMENTED** [review]
Thanks @Felix-Cadiz! A few suggestions:

- [ ] Could we shade the whole column instead of the component?
- [ ] Could we add some padding to the buttons so they don't touch the edges of the shaded region?
- [ ] Could you show how this looks on mobile?

**Comment by Felix-Cadiz** [comment]
- Shading is now the full column
- Twitter icon is now equal in size to the copy button
---- However, the hover effect is missing due to the TwitterIcon using an import from "React-share." I can try to make this happen manually, just let me know.
- Navigation buttons are adjusted to fit within their container.

I am having trouble working shading the mobile version of this section. I cannot find where all the components render as lines 49 - 60 of the OverviewHolder function in "policyengine-client/src/policyengine/pages/policy/overview.jsx" are not styling as I write.

Screen Shot 2022-08-11 at 10 33 39 AM
Screen Shot 2022-08-11 at 10 33 26 AM

**Comment by MaxGhenis** [comment]
Closing in favor of #916

**Pull request closed without merging**
