### PR TITLE
change bar graph color scheme

### LINKED ISSUE #127: Try green/gray color scheme instead of blue/gray

### LINKED ISSUE #233: Use gray for negative changes to decile and poverty charts
e.g. https://uk.policyengine.org/population-results?basic_rate=25 shows this:

image

Deciles with income loss should be gray, as well as population groups with higher poverty.

### PR DESCRIPTION
**Pull request by tolaouk**
fixes #127 
fixes #233

### CODE REVIEW

**Comment by tolaouk** [comment]
Ran into this error
https://gist.github.com/tolaouk/d0177947a064ebf4dbab9115c7e037f0

**Comment by tolaouk** [comment]
screenshots of population charts
image

image

image

**Comment by tolaouk** [comment]
image

**Comment by tolaouk** [comment]
changes to household charts
image

**Comment by MaxGhenis** [comment]
Cool - let's actually leave the baseline/reform charts as gray/blue and reserve gray/green for negative/positive changes.

Now that I'm seeing it, I think we should add #233 to this PR to avoid shading negative changes like poverty increases as green.

**Comment by tolaouk** [comment]
household charts with gray/blue
image

**Comment by tolaouk** [comment]
update charts to show grey for negative change and dark green for positive changes

image

image

image

**Review by nikhilwoodruff — APPROVED** [review]
Looks great to me- yes just the versioning and debugging, thanks @tolaouk !

**Comment by MaxGhenis** [comment]
Closing to recreate on a PolicyEngine branch

**Pull request closed without merging**
