### PR TITLE
Fix font issue

### PR DESCRIPTION
**Pull request by yuantaoz**
When users doesn't install the fonts, import the fonts from url.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thank you!! This has been bugging me forever lol

**Comment by yuantaoz** [comment]
> 

lol You are welcome! 😁

**Comment by yuantaoz** [comment]
> Thank you!! This has been bugging me forever lol

lol You are welcome! 😁

**Comment by nikhilwoodruff** [comment]
Thanks @yuantaoz - looks great. Could you just add an entry to the `changelog.yaml` file like in [this PR](https://github.com/PolicyEngine/policyengine/pull/548)?

**Comment by yuantaoz** [comment]
Sure, I have added an entry to changelog.yaml file.

**Pull request merged**
